#!/bin/bash

### This script is called after the user installs the application.
set -e
source "/var/apps/${TRIM_APPNAME}/cmd/common"

dbland_port=$(str_trim "$dbland_port")
if check_port_in_use "${dbland_port}"; then
    alarm_and_exit "端口 ${dbland_port} 已被占用，请更换端口后重试"
fi

exit 0